name: jhoo
description: A dart package to build websites using dart:html library
version: 0.0.1
repository: https://github.com/Ganeshsivakumar/jhoo

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  web: 

dependencies:
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

license: MIT
